// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: fx.proto

package fxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLiveRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveRateRequest) Reset() {
	*x = GetLiveRateRequest{}
	mi := &file_fx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveRateRequest) ProtoMessage() {}

func (x *GetLiveRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveRateRequest.ProtoReflect.Descriptor instead.
func (*GetLiveRateRequest) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{0}
}

func (x *GetLiveRateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetLiveRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	TsUnixNanos   int64                  `protobuf:"varint,3,opt,name=ts_unix_nanos,json=tsUnixNanos,proto3" json:"ts_unix_nanos,omitempty"`
	Stale         bool                   `protobuf:"varint,4,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveRateResponse) Reset() {
	*x = GetLiveRateResponse{}
	mi := &file_fx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveRateResponse) ProtoMessage() {}

func (x *GetLiveRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveRateResponse.ProtoReflect.Descriptor instead.
func (*GetLiveRateResponse) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{1}
}

func (x *GetLiveRateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetLiveRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *GetLiveRateResponse) GetTsUnixNanos() int64 {
	if x != nil {
		return x.TsUnixNanos
	}
	return 0
}

func (x *GetLiveRateResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

type GetNetExposureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetExposureRequest) Reset() {
	*x = GetNetExposureRequest{}
	mi := &file_fx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetExposureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetExposureRequest) ProtoMessage() {}

func (x *GetNetExposureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetExposureRequest.ProtoReflect.Descriptor instead.
func (*GetNetExposureRequest) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{2}
}

func (x *GetNetExposureRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetNetExposureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	NetAmount     float64                `protobuf:"fixed64,2,opt,name=net_amount,json=netAmount,proto3" json:"net_amount,omitempty"`
	HedgeCoverage float64                `protobuf:"fixed64,3,opt,name=hedge_coverage,json=hedgeCoverage,proto3" json:"hedge_coverage,omitempty"`
	OpenAmount    float64                `protobuf:"fixed64,4,opt,name=open_amount,json=openAmount,proto3" json:"open_amount,omitempty"`
	TsUnixNanos   int64                  `protobuf:"varint,5,opt,name=ts_unix_nanos,json=tsUnixNanos,proto3" json:"ts_unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetExposureResponse) Reset() {
	*x = GetNetExposureResponse{}
	mi := &file_fx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetExposureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetExposureResponse) ProtoMessage() {}

func (x *GetNetExposureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetExposureResponse.ProtoReflect.Descriptor instead.
func (*GetNetExposureResponse) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{3}
}

func (x *GetNetExposureResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetNetExposureResponse) GetNetAmount() float64 {
	if x != nil {
		return x.NetAmount
	}
	return 0
}

func (x *GetNetExposureResponse) GetHedgeCoverage() float64 {
	if x != nil {
		return x.HedgeCoverage
	}
	return 0
}

func (x *GetNetExposureResponse) GetOpenAmount() float64 {
	if x != nil {
		return x.OpenAmount
	}
	return 0
}

func (x *GetNetExposureResponse) GetTsUnixNanos() int64 {
	if x != nil {
		return x.TsUnixNanos
	}
	return 0
}

type StreamExposureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExposureRequest) Reset() {
	*x = StreamExposureRequest{}
	mi := &file_fx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExposureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExposureRequest) ProtoMessage() {}

func (x *StreamExposureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExposureRequest.ProtoReflect.Descriptor instead.
func (*StreamExposureRequest) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{4}
}

func (x *StreamExposureRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ExposureSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	NetAmount     float64                `protobuf:"fixed64,2,opt,name=net_amount,json=netAmount,proto3" json:"net_amount,omitempty"`
	HedgeCoverage float64                `protobuf:"fixed64,3,opt,name=hedge_coverage,json=hedgeCoverage,proto3" json:"hedge_coverage,omitempty"`
	OpenAmount    float64                `protobuf:"fixed64,4,opt,name=open_amount,json=openAmount,proto3" json:"open_amount,omitempty"`
	TsUnixNanos   int64                  `protobuf:"varint,5,opt,name=ts_unix_nanos,json=tsUnixNanos,proto3" json:"ts_unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExposureSnapshot) Reset() {
	*x = ExposureSnapshot{}
	mi := &file_fx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposureSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposureSnapshot) ProtoMessage() {}

func (x *ExposureSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposureSnapshot.ProtoReflect.Descriptor instead.
func (*ExposureSnapshot) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{5}
}

func (x *ExposureSnapshot) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ExposureSnapshot) GetNetAmount() float64 {
	if x != nil {
		return x.NetAmount
	}
	return 0
}

func (x *ExposureSnapshot) GetHedgeCoverage() float64 {
	if x != nil {
		return x.HedgeCoverage
	}
	return 0
}

func (x *ExposureSnapshot) GetOpenAmount() float64 {
	if x != nil {
		return x.OpenAmount
	}
	return 0
}

func (x *ExposureSnapshot) GetTsUnixNanos() int64 {
	if x != nil {
		return x.TsUnixNanos
	}
	return 0
}

type HedgePlanLeg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Notional      float64                `protobuf:"fixed64,2,opt,name=notional,proto3" json:"notional,omitempty"`
	Tenor         string                 `protobuf:"bytes,3,opt,name=tenor,proto3" json:"tenor,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ValueDate     string                 `protobuf:"bytes,5,opt,name=value_date,json=valueDate,proto3" json:"value_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HedgePlanLeg) Reset() {
	*x = HedgePlanLeg{}
	mi := &file_fx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HedgePlanLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HedgePlanLeg) ProtoMessage() {}

func (x *HedgePlanLeg) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HedgePlanLeg.ProtoReflect.Descriptor instead.
func (*HedgePlanLeg) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{6}
}

func (x *HedgePlanLeg) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *HedgePlanLeg) GetNotional() float64 {
	if x != nil {
		return x.Notional
	}
	return 0
}

func (x *HedgePlanLeg) GetTenor() string {
	if x != nil {
		return x.Tenor
	}
	return ""
}

func (x *HedgePlanLeg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HedgePlanLeg) GetValueDate() string {
	if x != nil {
		return x.ValueDate
	}
	return ""
}

type SubmitHedgePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Legs          []*HedgePlanLeg        `protobuf:"bytes,2,rep,name=legs,proto3" json:"legs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitHedgePlanRequest) Reset() {
	*x = SubmitHedgePlanRequest{}
	mi := &file_fx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitHedgePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitHedgePlanRequest) ProtoMessage() {}

func (x *SubmitHedgePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitHedgePlanRequest.ProtoReflect.Descriptor instead.
func (*SubmitHedgePlanRequest) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitHedgePlanRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SubmitHedgePlanRequest) GetLegs() []*HedgePlanLeg {
	if x != nil {
		return x.Legs
	}
	return nil
}

type HedgePlanLegResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	HedgeId       string                 `protobuf:"bytes,2,opt,name=hedge_id,json=hedgeId,proto3" json:"hedge_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Notional      float64                `protobuf:"fixed64,4,opt,name=notional,proto3" json:"notional,omitempty"`
	QuotedRate    float64                `protobuf:"fixed64,5,opt,name=quoted_rate,json=quotedRate,proto3" json:"quoted_rate,omitempty"`
	SlippageBps   float64                `protobuf:"fixed64,6,opt,name=slippage_bps,json=slippageBps,proto3" json:"slippage_bps,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HedgePlanLegResult) Reset() {
	*x = HedgePlanLegResult{}
	mi := &file_fx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HedgePlanLegResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HedgePlanLegResult) ProtoMessage() {}

func (x *HedgePlanLegResult) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HedgePlanLegResult.ProtoReflect.Descriptor instead.
func (*HedgePlanLegResult) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{8}
}

func (x *HedgePlanLegResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *HedgePlanLegResult) GetHedgeId() string {
	if x != nil {
		return x.HedgeId
	}
	return ""
}

func (x *HedgePlanLegResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HedgePlanLegResult) GetNotional() float64 {
	if x != nil {
		return x.Notional
	}
	return 0
}

func (x *HedgePlanLegResult) GetQuotedRate() float64 {
	if x != nil {
		return x.QuotedRate
	}
	return 0
}

func (x *HedgePlanLegResult) GetSlippageBps() float64 {
	if x != nil {
		return x.SlippageBps
	}
	return 0
}

func (x *HedgePlanLegResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubmitHedgePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Results       []*HedgePlanLegResult  `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Rejected      bool                   `protobuf:"varint,3,opt,name=rejected,proto3" json:"rejected,omitempty"`
	RejectReason  string                 `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitHedgePlanResponse) Reset() {
	*x = SubmitHedgePlanResponse{}
	mi := &file_fx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitHedgePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitHedgePlanResponse) ProtoMessage() {}

func (x *SubmitHedgePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitHedgePlanResponse.ProtoReflect.Descriptor instead.
func (*SubmitHedgePlanResponse) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitHedgePlanResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SubmitHedgePlanResponse) GetResults() []*HedgePlanLegResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SubmitHedgePlanResponse) GetRejected() bool {
	if x != nil {
		return x.Rejected
	}
	return false
}

func (x *SubmitHedgePlanResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

var File_fx_proto protoreflect.FileDescriptor

const file_fx_proto_rawDesc = "" +
	"\n" +
	"\bfx.proto\x12\x05fx.v1\"0\n" +
	"\x12GetLiveRateRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\"\x7f\n" +
	"\x13GetLiveRateResponse\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\x12\"\n" +
	"\rts_unix_nanos\x18\x03 \x01(\x03R\vtsUnixNanos\x12\x14\n" +
	"\x05stale\x18\x04 \x01(\bR\x05stale\"3\n" +
	"\x15GetNetExposureRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\"\xbf\x01\n" +
	"\x16GetNetExposureResponse\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"net_amount\x18\x02 \x01(\x01R\tnetAmount\x12%\n" +
	"\x0ehedge_coverage\x18\x03 \x01(\x01R\rhedgeCoverage\x12\x1f\n" +
	"\vopen_amount\x18\x04 \x01(\x01R\n" +
	"openAmount\x12\"\n" +
	"\rts_unix_nanos\x18\x05 \x01(\x03R\vtsUnixNanos\"3\n" +
	"\x15StreamExposureRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\"\xb9\x01\n" +
	"\x10ExposureSnapshot\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"net_amount\x18\x02 \x01(\x01R\tnetAmount\x12%\n" +
	"\x0ehedge_coverage\x18\x03 \x01(\x01R\rhedgeCoverage\x12\x1f\n" +
	"\vopen_amount\x18\x04 \x01(\x01R\n" +
	"openAmount\x12\"\n" +
	"\rts_unix_nanos\x18\x05 \x01(\x03R\vtsUnixNanos\"\x8f\x01\n" +
	"\fHedgePlanLeg\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bnotional\x18\x02 \x01(\x01R\bnotional\x12\x14\n" +
	"\x05tenor\x18\x03 \x01(\tR\x05tenor\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"value_date\x18\x05 \x01(\tR\tvalueDate\"Z\n" +
	"\x16SubmitHedgePlanRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12'\n" +
	"\x04legs\x18\x02 \x03(\v2\x13.fx.v1.HedgePlanLegR\x04legs\"\xd9\x01\n" +
	"\x12HedgePlanLegResult\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x19\n" +
	"\bhedge_id\x18\x02 \x01(\tR\ahedgeId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bnotional\x18\x04 \x01(\x01R\bnotional\x12\x1f\n" +
	"\vquoted_rate\x18\x05 \x01(\x01R\n" +
	"quotedRate\x12!\n" +
	"\fslippage_bps\x18\x06 \x01(\x01R\vslippageBps\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xa8\x01\n" +
	"\x17SubmitHedgePlanResponse\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x123\n" +
	"\aresults\x18\x02 \x03(\v2\x19.fx.v1.HedgePlanLegResultR\aresults\x12\x1a\n" +
	"\brejected\x18\x03 \x01(\bR\brejected\x12#\n" +
	"\rreject_reason\x18\x04 \x01(\tR\frejectReason2\xbe\x02\n" +
	"\x02FX\x12F\n" +
	"\vGetLiveRate\x12\x19.fx.v1.GetLiveRateRequest\x1a\x1a.fx.v1.GetLiveRateResponse\"\x00\x12O\n" +
	"\x0eGetNetExposure\x12\x1c.fx.v1.GetNetExposureRequest\x1a\x1d.fx.v1.GetNetExposureResponse\"\x00\x12K\n" +
	"\x0eStreamExposure\x12\x1c.fx.v1.StreamExposureRequest\x1a\x17.fx.v1.ExposureSnapshot\"\x000\x01\x12R\n" +
	"\x0fSubmitHedgePlan\x12\x1d.fx.v1.SubmitHedgePlanRequest\x1a\x1e.fx.v1.SubmitHedgePlanResponse\"\x00B9Z7github.com/ai-crypto-onramp/fx-hedging/proto/fx/v1;fxpbb\x06proto3"

var (
	file_fx_proto_rawDescOnce sync.Once
	file_fx_proto_rawDescData []byte
)

func file_fx_proto_rawDescGZIP() []byte {
	file_fx_proto_rawDescOnce.Do(func() {
		file_fx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fx_proto_rawDesc), len(file_fx_proto_rawDesc)))
	})
	return file_fx_proto_rawDescData
}

var file_fx_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fx_proto_goTypes = []any{
	(*GetLiveRateRequest)(nil),      // 0: fx.v1.GetLiveRateRequest
	(*GetLiveRateResponse)(nil),     // 1: fx.v1.GetLiveRateResponse
	(*GetNetExposureRequest)(nil),   // 2: fx.v1.GetNetExposureRequest
	(*GetNetExposureResponse)(nil),  // 3: fx.v1.GetNetExposureResponse
	(*StreamExposureRequest)(nil),   // 4: fx.v1.StreamExposureRequest
	(*ExposureSnapshot)(nil),        // 5: fx.v1.ExposureSnapshot
	(*HedgePlanLeg)(nil),            // 6: fx.v1.HedgePlanLeg
	(*SubmitHedgePlanRequest)(nil),  // 7: fx.v1.SubmitHedgePlanRequest
	(*HedgePlanLegResult)(nil),      // 8: fx.v1.HedgePlanLegResult
	(*SubmitHedgePlanResponse)(nil), // 9: fx.v1.SubmitHedgePlanResponse
}
var file_fx_proto_depIdxs = []int32{
	6, // 0: fx.v1.SubmitHedgePlanRequest.legs:type_name -> fx.v1.HedgePlanLeg
	8, // 1: fx.v1.SubmitHedgePlanResponse.results:type_name -> fx.v1.HedgePlanLegResult
	0, // 2: fx.v1.FX.GetLiveRate:input_type -> fx.v1.GetLiveRateRequest
	2, // 3: fx.v1.FX.GetNetExposure:input_type -> fx.v1.GetNetExposureRequest
	4, // 4: fx.v1.FX.StreamExposure:input_type -> fx.v1.StreamExposureRequest
	7, // 5: fx.v1.FX.SubmitHedgePlan:input_type -> fx.v1.SubmitHedgePlanRequest
	1, // 6: fx.v1.FX.GetLiveRate:output_type -> fx.v1.GetLiveRateResponse
	3, // 7: fx.v1.FX.GetNetExposure:output_type -> fx.v1.GetNetExposureResponse
	5, // 8: fx.v1.FX.StreamExposure:output_type -> fx.v1.ExposureSnapshot
	9, // 9: fx.v1.FX.SubmitHedgePlan:output_type -> fx.v1.SubmitHedgePlanResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fx_proto_init() }
func file_fx_proto_init() {
	if File_fx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fx_proto_rawDesc), len(file_fx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fx_proto_goTypes,
		DependencyIndexes: file_fx_proto_depIdxs,
		MessageInfos:      file_fx_proto_msgTypes,
	}.Build()
	File_fx_proto = out.File
	file_fx_proto_goTypes = nil
	file_fx_proto_depIdxs = nil
}
