// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: fx.proto

package fxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FX_GetLiveRate_FullMethodName     = "/fx.v1.FX/GetLiveRate"
	FX_GetNetExposure_FullMethodName  = "/fx.v1.FX/GetNetExposure"
	FX_StreamExposure_FullMethodName  = "/fx.v1.FX/StreamExposure"
	FX_SubmitHedgePlan_FullMethodName = "/fx.v1.FX/SubmitHedgePlan"
)

// FXClient is the client API for FX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FX service exposes live FX rates and aggregate exposure / hedge execution
// consumed by Pricing / Quote and Treasury Orchestration.
type FXClient interface {
	// GetLiveRate returns the cached live FX rate for a currency (vs USD).
	GetLiveRate(ctx context.Context, in *GetLiveRateRequest, opts ...grpc.CallOption) (*GetLiveRateResponse, error)
	// GetNetExposure returns the current net exposure for a currency.
	GetNetExposure(ctx context.Context, in *GetNetExposureRequest, opts ...grpc.CallOption) (*GetNetExposureResponse, error)
	// StreamExposure streams exposure snapshots for a currency until the
	// client cancels the stream.
	StreamExposure(ctx context.Context, in *StreamExposureRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExposureSnapshot], error)
	// SubmitHedgePlan submits a batched hedge plan from Treasury Orchestration
	// and returns per-leg results.
	SubmitHedgePlan(ctx context.Context, in *SubmitHedgePlanRequest, opts ...grpc.CallOption) (*SubmitHedgePlanResponse, error)
}

type fXClient struct {
	cc grpc.ClientConnInterface
}

func NewFXClient(cc grpc.ClientConnInterface) FXClient {
	return &fXClient{cc}
}

func (c *fXClient) GetLiveRate(ctx context.Context, in *GetLiveRateRequest, opts ...grpc.CallOption) (*GetLiveRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLiveRateResponse)
	err := c.cc.Invoke(ctx, FX_GetLiveRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXClient) GetNetExposure(ctx context.Context, in *GetNetExposureRequest, opts ...grpc.CallOption) (*GetNetExposureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetExposureResponse)
	err := c.cc.Invoke(ctx, FX_GetNetExposure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXClient) StreamExposure(ctx context.Context, in *StreamExposureRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExposureSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FX_ServiceDesc.Streams[0], FX_StreamExposure_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamExposureRequest, ExposureSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FX_StreamExposureClient = grpc.ServerStreamingClient[ExposureSnapshot]

func (c *fXClient) SubmitHedgePlan(ctx context.Context, in *SubmitHedgePlanRequest, opts ...grpc.CallOption) (*SubmitHedgePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitHedgePlanResponse)
	err := c.cc.Invoke(ctx, FX_SubmitHedgePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FXServer is the server API for FX service.
// All implementations must embed UnimplementedFXServer
// for forward compatibility.
//
// FX service exposes live FX rates and aggregate exposure / hedge execution
// consumed by Pricing / Quote and Treasury Orchestration.
type FXServer interface {
	// GetLiveRate returns the cached live FX rate for a currency (vs USD).
	GetLiveRate(context.Context, *GetLiveRateRequest) (*GetLiveRateResponse, error)
	// GetNetExposure returns the current net exposure for a currency.
	GetNetExposure(context.Context, *GetNetExposureRequest) (*GetNetExposureResponse, error)
	// StreamExposure streams exposure snapshots for a currency until the
	// client cancels the stream.
	StreamExposure(*StreamExposureRequest, grpc.ServerStreamingServer[ExposureSnapshot]) error
	// SubmitHedgePlan submits a batched hedge plan from Treasury Orchestration
	// and returns per-leg results.
	SubmitHedgePlan(context.Context, *SubmitHedgePlanRequest) (*SubmitHedgePlanResponse, error)
	mustEmbedUnimplementedFXServer()
}

// UnimplementedFXServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFXServer struct{}

func (UnimplementedFXServer) GetLiveRate(context.Context, *GetLiveRateRequest) (*GetLiveRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLiveRate not implemented")
}
func (UnimplementedFXServer) GetNetExposure(context.Context, *GetNetExposureRequest) (*GetNetExposureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetExposure not implemented")
}
func (UnimplementedFXServer) StreamExposure(*StreamExposureRequest, grpc.ServerStreamingServer[ExposureSnapshot]) error {
	return status.Error(codes.Unimplemented, "method StreamExposure not implemented")
}
func (UnimplementedFXServer) SubmitHedgePlan(context.Context, *SubmitHedgePlanRequest) (*SubmitHedgePlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitHedgePlan not implemented")
}
func (UnimplementedFXServer) mustEmbedUnimplementedFXServer() {}
func (UnimplementedFXServer) testEmbeddedByValue()            {}

// UnsafeFXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FXServer will
// result in compilation errors.
type UnsafeFXServer interface {
	mustEmbedUnimplementedFXServer()
}

func RegisterFXServer(s grpc.ServiceRegistrar, srv FXServer) {
	// If the following call panics, it indicates UnimplementedFXServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FX_ServiceDesc, srv)
}

func _FX_GetLiveRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiveRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServer).GetLiveRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FX_GetLiveRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServer).GetLiveRate(ctx, req.(*GetLiveRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FX_GetNetExposure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetExposureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServer).GetNetExposure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FX_GetNetExposure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServer).GetNetExposure(ctx, req.(*GetNetExposureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FX_StreamExposure_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamExposureRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FXServer).StreamExposure(m, &grpc.GenericServerStream[StreamExposureRequest, ExposureSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FX_StreamExposureServer = grpc.ServerStreamingServer[ExposureSnapshot]

func _FX_SubmitHedgePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitHedgePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServer).SubmitHedgePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FX_SubmitHedgePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServer).SubmitHedgePlan(ctx, req.(*SubmitHedgePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FX_ServiceDesc is the grpc.ServiceDesc for FX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fx.v1.FX",
	HandlerType: (*FXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLiveRate",
			Handler:    _FX_GetLiveRate_Handler,
		},
		{
			MethodName: "GetNetExposure",
			Handler:    _FX_GetNetExposure_Handler,
		},
		{
			MethodName: "SubmitHedgePlan",
			Handler:    _FX_SubmitHedgePlan_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamExposure",
			Handler:       _FX_StreamExposure_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fx.proto",
}
